// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// Replace placeholder values by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Then download google-services.json → android/app/
// and GoogleService-Info.plist → ios/Runner/

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured {
    try {
      final options = currentPlatform;
      return !options.apiKey.contains('REPLACE_ME');
    } catch (_) {
      return false;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Firebase is not configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Firebase is not supported on this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-IwFSwch8wQrMtTMi84uN-86YZAoyp4s',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'kelseyapp',
    storageBucket: 'kelsey-homestay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-IwFSwch8wQrMtTMi84uN-86YZAoyp4s',
    appId: '1:1054268836066:ios:4606c441700d743886f6bb',
    messagingSenderId: '000000000000',
    projectId: 'kelseyapp',
    storageBucket: 'kelsey-homestay.firebasestorage.app',
    iosBundleId: 'com.example.kelseyapp',
  );
}
